FROM node:20-alpine
ARG DATABASE_URL
WORKDIR /app

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm && \
  pnpm install

COPY prisma ./prisma

COPY . .

EXPOSE 3000

CMD ["pnpm", "dev:docker"]
