services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - DATABASE_URL=postgresql://user:password@db:5432/next-starter?schema=public
    container_name: next-starter
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/next-starter?schema=public
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - "/app/.next"
      - "/app/node_modules"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:alpine
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: next-starter
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
